### ISSUE TITLE
Modification. Foldering vertex groups.

### ISSUE THREAD

**Issue by DinozavrNenarkoman** [MontagueMGM/shape_keys_plus#10]
Hello there, it would be good addition to have folderable vertex groups also, they also use similar panel to shape keys.
It could be helpful to sort large amount of vert groups and use tree foldering to hierarchy them just like bones, surely it will undoubtedly make it perfect.

**Comment by MontagueMGM** [comment]
I can't code this with the method I used to implement shape key folders. Both shape keys and vertex groups are incapable of custom properties, so I had to store folder data in the shape key's `vertex_group` attribute, in the form of text-based data chunks. A vertex group doesn't have such a place for me to store those chunks.

Even if I knew how to do this, I think modifying the vertex groups panel is overextending the add-on's features. A lot of lists in Blender, such as materials and brushes, can benefit from this kind of hierarchy interface, but that would have to be an entirely new add-on. For the sake of simplicity and clean integration in various workflows, the features of Shape Keys+ should stay in the Shape Keys+ panel.
