### ISSUE TITLE
Enhancement: improve "new folder" create performance

### ISSUE THREAD

**Issue by Fak3** [MontagueMGM/shape_keys_plus#6]
I have a file with 100+ shape keys, and when i clicked "new folder" in the shape keys panel, the cpu load went 100%, and only after a minute it finished and created the folder. Reproducible: every time.

Update: apparently it works quite fast if the last shape key in the list is selected. Only if first shape key is selected, it takes about a minute to complete.

Blender version: 2.83
Addon version: git master

**Comment by Fak3** [comment]
The same issue with moving shape keys to folder - takes about a minute to complete.

**Comment by MontagueMGM** [comment]
This can't be completely fixed from my end; see the pinned issue #2: Blender doesn't provide a way to insert a shape key directly to a specific index in the list, so I have to move them there from the bottom, one index at a time.

I feel like there's an easy fix to this in the C side of Blender considering the "Move to Top" operator of the original Shape Keys panel sends the shape key directly to index 1, which is the simple functionality I would need in Python to easily solve this issue. But I don't know C or Blender's internal source code, so I can't do that myself.
