### ISSUE TITLE
Folders given value

### ISSUE THREAD

**Issue by Kovadon** [MontagueMGM/shape_keys_plus#9]
In situations where the shapekeys need to be in a specific order to be controlled by drivers/other sources, folders act as a shapekey and end up throwing off the entire order of shapekeys. Fixed by deleting folder, which is a shame I really like the organization it provides.

**Comment by MontagueMGM** [comment]
Folders _are_ shape keys, they have to be in order to appear in the list. For the moment, the driver issue may be solved in various ways (depending on your use cases) on the user's end by checking to see if the shape key is a folder with `ShapeKey.vertex_group.startswith("SKP.")`.
